//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruxMonies
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestInfo
    {
        public int IntId { get; set; }
        public int MemberId { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public Nullable<System.DateTime> InterestDate { get; set; }
        public Nullable<decimal> InterestDue { get; set; }
        public Nullable<decimal> Total { get; set; }
    }
}
