//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CruxMonies
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string AccountName { get; set; }
        public string PhoneNo { get; set; }
        public string AccountNo { get; set; }
        public string BankName { get; set; }
        public string Email { get; set; }
        public string NameOfFile { get; set; }
        public string UserId { get; set; }
        public System.DateTime Date { get; set; }
    }
}
